const API_HOST_BASE_URL = "https://api.noroff.dev/api/v1";
const API_AUCTION_BASE = "/auction";
const API_REGISTER_BASE = "/auth/register";
const API_LOGIN_BASE = "/auth/login";
const API_PROFILE_BASE = "/profiles";
const API_LISTINGS_BASE = "/listings";

const API_LOGIN_URL = `${API_HOST_BASE_URL}${API_AUCTION_BASE}${API_LOGIN_BASE}`;

const API_REGISTER_URL = `${API_HOST_BASE_URL}${API_AUCTION_BASE}${API_REGISTER_BASE}`;

const API_PROFILE_URL = `${API_HOST_BASE_URL}${API_AUCTION_BASE}${API_PROFILE_BASE}`;

const API_LISTINGS_URL = `${API_HOST_BASE_URL}${API_AUCTION_BASE}${API_LISTINGS_BASE}`;

export { API_REGISTER_URL, API_LOGIN_URL, API_PROFILE_URL, API_LISTINGS_URL };
